# Usando Node 22 para desenvolvimento
FROM node:22-alpine

# Define diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala dependências
RUN npm install

# Expõe a porta usada pelo Vite ou outro dev server
EXPOSE 5173

# Comando padrão
CMD ["npm", "run", "dev"]