services:
  backend:
    image: "${PROJECT_NAME}/backend:${BACKEND_IMAGE_VERSION}"
    container_name: "${PROJECT_NAME}-backend"
    restart: "no"
    volumes:
      - ./backend/storage:/var/www/html/storage
      - ./backend/.env:/var/www/html/.env
    networks:
      - default

  frontend:
    image: "${PROJECT_NAME}/frontend:${FRONTEND_IMAGE_VERSION}"
    container_name: "${PROJECT_NAME}-frontend"
    restart: "no"
    environment:
      TZ: 'America/Sao_Paulo'
      NODE_OPTIONS: "--dns-result-order=ipv4first"
    networks:
      - default

networks:
  default:
    driver: bridge