services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    environment:
      USER_ID: "${USER_ID:?}"
      GROUP_ID: "${GROUP_ID:?}"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    command: yarn run start:dev
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - ./frontend:/usr/src/app
    command: [ "yarn", "dev" ]
    networks:
      - default

  postgres:
    image: postgres:17.5
    container_name: "${PROJECT_NAME}-postgres"
    restart: "no"
    environment:
      POSTGRES_USER: "${DB_USERNAME:?Usuário postgres não foi definido}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?Senha do usuário postgres não foi definida}"
      POSTGRES_DB: "${DB_DATABASE:-dev_database}"
    volumes:
      - ./data/postgres-${BRANCH_NAME:-main}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:5432"
    networks:
      - default

#  nginx:
#    image: "${PROJECT_NAME}/nginx:${NGINX_IMAGE_VERSION}"
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: "${PROJECT_NAME}-nginx"
#    restart: "no"
#    environment:
#      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx/sites-enabled"
#      SERVER_HOST: "${SERVER_HOST:-localhost}"
#      SERVER_PORT: "${SERVER_PORT:-9001}"
#      SERVER_PORT_SSL: "${SERVER_PORT_SSL:-9000}"
#    volumes:
#      # Volumes npm
#      -
#      # Volumes de dados
#      - ./nginx/logs:/var/log/nginx
#      # Volumes de configurações
#      - ./nginx/server-conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/server-conf/conf.d:/etc/nginx/conf.d
#      - ./nginx/server-conf/sites-available:/etc/nginx/sites-available
#      - ./nginx/server-conf/sites-enabled:/etc/nginx/sites-enabled
#      - ./nginx/server-conf/snippets:/etc/nginx/snippets
#      - ./nginx/server-conf/ssl:/etc/nginx/ssl
#      - ./nginx/server-conf/templates/default.conf.template:/etc/nginx/templates/default.conf.template
#    expose:
#      - "${SERVER_PORT:-9001}"
#      - "${SERVER_PORT_SSL:-9000}"
#    ports:
#      - "${SERVER_PORT:-9001}:${SERVER_PORT:-9001}"
#      - "${SERVER_PORT_SSL:-9000}:${SERVER_PORT_SSL:-9000}"
#    command: [ "nginx-debug", "-g", "daemon off;" ]
#    networks:
#      - default

