services:
  backend:
    environment:
      - PORT=${BACKEND_PORT:-3001}
    ports:
      - "${BACKEND_PORT:-3001}:${BACKEND_PORT:-3001}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=${BACKEND_PORT:-3001}"

  frontend:
    environment:
      - PORT=${FRONTEND_PORT:-3000}
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=${FRONTEND_PORT:-3000}"

  traefik:
    image: "${PROJECT_NAME}/traefik:${TRAEFIK_IMAGE_VERSION:?}"
    build:
      context: ./traefik
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-traefik"
    entrypoint: ["/etc/traefik/server-conf/traefik-entrypoint.sh"]
    env_file:
      - ./traefik/.env.traefik
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config/traefik.yml:/etc/traefik/config/traefik.yml:ro
      - ./traefik/config/dynamic.yml:/etc/traefik/config/dynamic.yml:ro
      - ./traefik/server-conf/traefik-entrypoint.sh:/etc/traefik/server-conf/traefik-entrypoint.sh
      - ./data/traefik/certs:/etc/traefik/certs
      - ./data/traefik/log:/var/log
    networks:
      - default