global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # use docker socket
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml  # só se você estiver usando mesmo

api:
  dashboard: true
  insecure: true