#!/usr/bin/env bash

if [[ "$DOCKER_ENV" == "local" || "$DOCKER_ENV" == "testing" ]]; then
    mkdir -p "$PROJECT_ROOT/data"

    BRANCH_NAME="main"
    export BRANCH_NAME

    # Inicializa o .env do NestJS
    if [[ ! -f "$PROJECT_ROOT/backend/.env" && -f "$PROJECT_ROOT/backend/.env.example" ]]; then
        cp -a "$PROJECT_ROOT/backend/.env.example" "$PROJECT_ROOT/backend/.env"
        GENERATE_BACKEND_KEYS="yes"
    fi

    # Evita que alguns comandos sejam executados mais de uma vez
    if ! [[ "${args[0]}" =~ ^(build|composer|yarn)$ ]]; then
        ###
        ## Frontend
        ###
        # Instala as dependências do Node usado o yarn
        if [[ ! -d "$PROJECT_ROOT/frontend/node_modules/" ]]; then
            docker-compose run --rm frontend yarn
        fi
    fi

    ###
    ## Geral
    ###

    if [[ "$SERVER_TYPE" == "nginx" ]]; then
    # Gera as chaves para a conexão SSL do Nginx
      if [[ ! -f "$PROJECT_ROOT/nginx/server-conf/ssl/self-signed.key" || ! -f "$PROJECT_ROOT/nginx/server-conf/ssl/self-signed.crt" ]]; then
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -subj "/C=BR/ST=GO/L=Goiânia/O=NúcleoGov/CN=$SERVER_HOST/emailAddress=contato@$SERVER_HOST" \
              -keyout "$PROJECT_ROOT/nginx/server-conf/ssl/self-signed.key" -out "$PROJECT_ROOT/nginx/server-conf/ssl/self-signed.crt"
      fi
    else
      # Gera as chaves para a conexão SSL do Traefik
      TRAEFIK_DIR="$PROJECT_ROOT/traefik"

      # Inicializa o .env.traefik
      if [[ ! -f "$TRAEFIK_DIR/.env.traefik" && -f "$TRAEFIK_DIR/.env.example" ]]; then
          cp -a "$TRAEFIK_DIR/.env.example" "$TRAEFIK_DIR/.env.traefik"
      fi

      # Carrega as variáveis de domínio do .env.traefik para o ambiente do shell
      if [[ -f "$TRAEFIK_DIR/.env.traefik" ]]; then
          export $(grep -E '^(FRONTEND_DOMAIN|BACKEND_DOMAIN|TRAEFIK_IMAGE_VERSION|FRONTEND_PORT|BACKEND_PORT)' "$TRAEFIK_DIR/.env.traefik" | xargs)
      fi

    fi

    # Habilita o novo formato de build do docker
    export DOCKER_BUILDKIT=1
fi
